spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23lixWFOmTPqi09xhD
            client-secret: 1718e8f92685f9e192913df772ad69f20f31fe55
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: user:email,read:user
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login